# Docker
trigger:
- main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env'
        retryCount: '5'
    - task: DockerCompose@0
      inputs:
       containerregistrytype: 'Container Registry'
       dockerRegistryEndpoint: 'Docker Hub'
       projectName: 'noorairene/cert-backend'
       dockerComposeFile: '**/docker-compose.yml'
       action: 'Push services'
       includeLatestTag: true

