# Docker
trigger:
- main

resources:
- repo: self

variables:
   tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env'
        retryCount: '5'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'noorairene/cert-backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'noorairene/cert-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'