# Docker
trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Back and front
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env'
        retryCount: '5'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'noorairene/cert-backend'
        tags: 'back'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'noorairene/cert-frontend'
        tags: 'front'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'