version: '3.8'
services:
  backend:
    build: ./backend
    image: certificates/back
    container_name: certificates-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    image: certificates/front
    container_name: certificates-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src #code changes are instantly reflected to running container
    stdin_open: true
    tty: true
    depends_on:
      - backend
